version: "3.2"

services:
  books-postgres:
    image: registry.k8.wildwidewest.xyz/repository/docker-repository/books/postgres
    build:
      context: ../books-postgres
    ports:
      - 5432:5432
  books-api:
    image: registry.k8.wildwidewest.xyz/repository/docker-repository/books/api
    build:
      context: ../books-api
    environment:
      - spring.datasource.url=jdbc:postgresql://books-postgres:5432/apibook
    depends_on:
      - books-postgres
    ports:
      - 8080:8080
  books-gui:
    image: registry.k8.wildwidewest.xyz/repository/docker-repository/books/gui
    build:
      context: ../books-gui
    environment:
      - books_api_url=books-api
    depends_on:
      - books-api
    volumes:
      - $books_gui_dir:/usr/share/nginx/html
    ports:
      - 80:80