version: "3.2"

services:
  books-postgres:
    image: registry.k8.wildwidewest.xyz/repository/docker-repository/books/postgres
    build:
      context: ../books-postgres
    ports:
      - 5432:5432
  books-api:
    image: registry.k8.wildwidewest.xyz/repository/docker-repository/books/api
    build:
      context: ../books-api
    environment:
      - spring.datasource.url=jdbc:postgresql://books-postgres:5432/apibook
#    healthcheck:
#      test: http://localhost:8080/health
    depends_on:
      - books-postgres
    ports:
      - 8080:8080
  books-gui:
    image: registry.k8.wildwidewest.xyz/repository/docker-repository/books/gui
    build:
      context: ../books-gui
    depends_on:
      - books-api
    volumes:
      - /home/elkouhen/dev/meltingpoc/books-gui:/usr/share/nginx/html
    ports:
      - 80:80